USERNAME = "username"
PASSWORD = "password"
LOGIN_API = "https://watertel.com/api/login"
MESSAGE_API = "https://watertel.com/api/sms?accessToken={access_token}"
MILIO_MESSAGE_API = "https://milio-sms-gateway.com/api/sms?accessToken={access_token}"
REGISTERED_PHONE = "1234567890"